### ISSUE TITLE
How many encoders one rp2040 chip can read?

### ISSUE THREAD

**Issue by mxyxbb** [SebKuzminsky/rp2040-rotary-encoder#1]
Hello, thanks for your code! 
It successfully works on my pico board ( reading one ec11 encoder).
I am wondering now that how many encoders one rp2040 chip can read based on this lib.
Since every state machine has their own ISR, OSR, X ,Y and PC, does that mean every state machine can reuse the PIO program?
So I can read up to 16 encoders?
Looking forward to your reply!

**Comment by SebKuzminsky** [comment]
Hi @mxyxbb, I'm glad to hear this is working for you.

The code is currently set up for just one encoder input, because that's what i needed in my application.  It should be relatively easy to modify it to support more encoders.  I'd be happy to review a PR to add this functionality. 

You'd probably want to make a struct for each encoder input.  The struct would hold the `quadrature_pio` and `quadrature_sm` variables of the driver, and the `pin` argument to the `quadrature_encoder_program_init()` function.  Have the caller make a struct for each encoder input and call the initialization function with that struct.  Be careful to manage the max step rate, because it's determined by the PIO frequency, which affects all state machines of the PIO unit.
